version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Azure.WebJobs.Extensions.Storage
    versions:
    - 4.0.3
  - dependency-name: Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator
    versions:
    - 1.2.0
